### ISSUE TITLE
Rare crash with getBlastReduction in safecrystal branch 

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#613]
Latest commit. Notice line 424 calling the method which crashes at line 446. 
@pol-y-mer plox fix pls

Apparently the person was doing nothing so this could be caused by null entity or something?

[L#424](https://github.com/S-B99/kamiblue/blob/08410d50174f77e5cd8fd3e9059fe4f2e621cadc/src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java#L424)
[L#446](https://github.com/S-B99/kamiblue/blob/08410d50174f77e5cd8fd3e9059fe4f2e621cadc/src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java#L446)
<details>
    <summary>Stacktrace</summary>

```
[12:48:21] [main/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_74]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_74]
        at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[?:1.8.0_74]
        at java.util.HashSet.<init>(HashSet.java:119) ~[?:1.8.0_74]
        at com.google.common.collect.Sets.newHashSet(Sets.java:273) ~[guava-21.0.jar:?]
        at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_180375_b(SourceFile:204) ~[wh.class
        at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111129_g(SourceFile:186) ~[wh.class
        at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111126_e(SourceFile:176) ~[wh.class
        at net.minecraft.entity.EntityLivingBase.func_70658_aO(EntityLivingBase.java:1343) ~[vp.class:?]
        at me.zeroeightsix.kami.module.modules.combat.CrystalAura.getBlastReduction(CrystalAura.java:446) ~[Crysta
        at me.zeroeightsix.kami.module.modules.combat.CrystalAura.calculateDamage(CrystalAura.java:424) ~[CrystalA
        at me.zeroeightsix.kami.module.modules.combat.CrystalAura.onUpdate(CrystalAura.java:288) ~[CrystalAura.cla
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_74]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_74]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_74]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_74]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_74]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_74]
        at me.zeroeightsix.kami.module.ModuleManager.onUpdate(ModuleManager.java:58) ~[ModuleManager.class:?]
        at me.zeroeightsix.kami.event.ForgeEventProcessor.onTick(ForgeEventProcessor.java:73) ~[ForgeEventProcesso
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_74_ForgeEventProcessor_onTick_ClientTickEven
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHa
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349) ~[FMLCommonH
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1910) ~[bib.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) ~[bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

</details>

**Comment by pol-y-mer** [comment]
i didnt write that :floshed:

**Comment by pol-y-mer** [comment]
i only wrote the multiplace idk why thats happening but i can try and fix it

**Comment by Vonr** [comment]
any reproduction steps?

**Comment by S-B99** [comment]
ask @TobSick

**Comment by Vonr** [comment]
whats his discord?

**Comment by S-B99** [comment]
70651 in kami blue discord

all he told me was he wasn't doing anything. 

I can't reproduce this

**Comment by TobSick** [comment]
It is caused by a null entity

**Comment by S-B99** [comment]
yes but how did you get a null entity?

**Comment by S-B99** [comment]
Closing this as won't fix until I can reproduce this issue.
